[jobs.lab1]

image = { source = "dockerfile", path = ".", tag = "lab1" }

run = [
  "java Main $input  $ir",
]

[jobs.lab2]

image = { source = "dockerfile", path = ".", tag = "lab2" }

run = [
  "java Main $input  $ir",
]

[jobs.lab3]

image = { source = "dockerfile", path = ".", tag = "lab3" }

run = [
  "java Main $input  $ir",
]

[jobs.lab4]

image = { source = "dockerfile", path = ".", tag = "lab4" }

run = [
  "java Main $input $ir",
]

[jobs.lab5]

image = { source = "dockerfile", path = ".", tag = "lab5" }

run = [
  "java Main $input $ir",
]

[jobs.lab6]

image = { source = "dockerfile", path = ".", tag = "lab6" }

run = [
  "java Main $input $ir",
]