public enum ASTNodeType {
    number, ident,
    CONST, INT, VOID, IF, ELSE, WHILE, BREAK, CONTINUE, RETURN,
    COMMA, SEMICOLON, ASSIGN,
    BRACE_L_PLUS, BRACE_R_PLUS, BRACE_L_MEDIUM, BRACE_R_MEDIUM, BRACE_L, BRACE_R,
    PLUS, MINUS, MUL, DIV, NOT, MOD, GT, LT, GT_EQ, LT_EQ, EQ, NOT_EQ, AND, OR,
    compUnit,
    decl,
    constDecl,
    BType,
    constDef,
    constInitial,
    varDecl,
    varDef,
    initVal,
    funcDef,
    funcType,
    funcFParams,
    funcFParam,
    block,
    blockItem,
    stmt,
    exp,
    cond,
    lVal,
    primaryExp,
    unaryExp,
    unaryOp,
    funcRParams,
    mulExp,
    addExp,
    relExp,
    eqExp,
    lAndExp,
    lOrExp,
    constExp,
}
